### ISSUE TITLE
Error Building FSharp on MacOSX - Microsoft.Portable.FSharp.Targets

### ISSUE THREAD

**Issue by evolvedmicrobe** [fsharp/fsharp#391]
If I clone F# and try to build it on MacOSX pointing to a 64 bit version of mono 3.12 compiled from the source tarball (autogen.sh --prefix = $HOME/mono64), then make fails with the following error:

    Target _CopyDeployFilesToOutputDirectoryPreserveNewest:
    /Users/myname/mono64/lib/mono/4.5/Microsoft.Common.targets: error : Cannot copy /Users/myname/git/fsharp/src/fsharp/FSharp.Build/Microsoft.Portable.FSharp.Targets to /Users/myname/git/fsharp/lib/release/Microsoft.Portable.FSharp.Targets, as the source file doesn't exist.
    	Task "Copy" execution -- FAILED
    	Done building target "_CopyDeployFilesToOutputDirectoryPreserveNewest" in project "/Users/myname/git/fsharp/src/fsharp/FSharp.Build/FSharp.Build.fsproj".-- FAILED
    Done building project "/Users/myname/git/fsharp/src/fsharp/FSharp.Build/FSharp.Build.fsproj".-- FAILED    

    Build FAILED.

The error appears to be due to the following section of src/FSharp/FSharp.Build/FSharp.Build.fsproj

     <None Include="Microsoft.Portable.FSharp.Targets">
          <Link>Microsoft.Portable.FSharp.Targets</Link>
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
     </None>

If I delete this section, the build proceeds but then dies much later with: 

    mono64/lib/mono/4.5/Microsoft.Common.targets: error : PCL Reference Assemblies not installed.

It looks like @mexx removed the Microsoft.Portable.FSharp.targets file with commit f34dec8 in December, and there has been some discussion of the PCLs and these types of issues on the web.  Anyone know a quick fix?

**Comment by mexx** [comment]
Yes, you're right, I removed the duplicate file `Microsoft.Portable.FSharp.targets`.
The correct one `Microsoft.Portable.FSharp.Targets` is still in repository and should be found.
I know about the problem when pulling the change on Windows, see my comment on [#362](https://github.com/fsharp/fsharp/pull/362#issuecomment-66891078), maybe it's same problem on MacOS?

**Comment by evolvedmicrobe** [comment]
I tried reverting but did not get very far and wound up with the same missing PCL libraries errors.

I was however able to fix this problem by removing the monotouch and portable builds.

In particular, by editing MakeFile.in to change line 3 as:

    -all clean install build build-proto all-monotouch-monodroid all-monotouch all-monodroid:
    +all clean install build build-proto

 And editing src/fsharp/Makefile.in to delete from lines 50 - 62 the following:

     ifeq ("$(pclenabled47)", "yes")
    	$(MAKE) -C FSharp.Core TargetFramework=portable47 $@
    	$(MAKE) -C FSharp.Core FSharpCoreBackVersion=3.0 TargetFramework=portable47 $@
    endif
    ifeq ("$(pclenabled7)", "yes")
    	$(MAKE) -C FSharp.Core TargetFramework=portable7 $@
    endif
    ifeq ("$(pclenabled78)", "yes")
    	$(MAKE) -C FSharp.Core TargetFramework=portable78 $@
    endif
    ifeq ("$(pclenabled259)", "yes")
    	$(MAKE) -C FSharp.Core TargetFramework=portable259 $@
    endif

These changes allow me to cleanly make fsharp on Mac OSX with a 64 bit mono install.  

Do we need the monotouch builds and this PCL stuff?  Could these be removed?

**Comment by 7sharp9** [comment]
Yes it is needed, otherwise F# wouldn't work on Android, ios, or PCL

**Comment by evolvedmicrobe** [comment]
Can certainly understand that.  With that said, am not sure how to deal with the fact that (at least following the standard build process in my hands), it doesn't seem to compile on 64 bit Mac OSX.

I have a work around for myself, but if anyone more familiar with the build process could enable it to work without it, would be great.  Feel free to close the issue otherwise though.

**Comment by dsyme** [comment]
@7sharp9 @evolvedmicrobe  - The build should be fixed to always work on Mac OSX 64-bit.  It should be adjusted to "do the right thing" if monotouch and PCL bits are not available on the machine where the build is being performed.

@evolvedmicrobe - do you think you could adjust the configure.ac and any other related parts of the build for these cases, and test on Mac OSX 64-bit?  See https://github.com/fsharp/fsharp/blob/master/configure.ac#L70 for example where we detect PCL for example.

**Comment by dsyme** [comment]
I'm closing this since #391 has been merged, @evolvedmicrobe please check on Mac OSX 64-bit build if you get the chance, thanks

**Comment by 7sharp9** [comment]
F# always compiles on osx with a 32bit mono.  64bit Mono, I don't know.

**Comment by evolvedmicrobe** [comment]
So the problem still shows up, but the patch nearly fixes it, there just remains a problem with PKG_CONFIG.  The should only happen to people who have both a 64 bit and 32 bit mono installed.  

In particular, with the 52df5ac patch, I found that it would still set PCLENABLED47 with the test below:

    if test -e $MONOLIBDIR/mono/xbuild-frameworks/.NETPortable/v4.0/Profile/Profile47/mscorlib.dll; then
       PCLENABLED47=yes
    else
       PCLENABLED47=no
    fi

The reason was that it appeared to be setting $MONOLIBDIR to the 32 bit mono install location, not the 64 bit location.  If I explicitly set the PKG_CONFIG_PATH prior to starting the build process as below, it works just fine.

    export PKG_CONFIG_PATH=$MONO_PATH/lib/pkgconfig/
    ./autogen.sh --prefix=$MONO_PATH
    make

Perhaps the average user will already know about the PKG_CONFIG_PATH issue, though it might be nice avoid setting that environmental variable or maybe add a note to the documentation for users with 32/64 bit installs.

Thanks for the fix!

**Comment by knocte** [comment]
> Perhaps the average user will already know about...

I don't think the average user would have two parallel monos installed (32bit and 64bit)?

**Comment by royalstream** [comment]
> I don't think the average user would have two parallel monos installed (32bit and 64bit)?

I wouldn't be so sure, installing Xamarin is pretty common for the average user (32bit mono). At the same time having to deal with native libraries which require 64bit mono is not that uncommon either.

I may be a seasoned F# developer on Windows but regarding Mono/Mac I'm a total newbie and if this issue happened to me, I'm sure it's happening to many newcomers out there.

**Comment by 7sharp9** [comment]
With no official 64bit OSX on mono this is always going to be fiddly IMHO.  I've never had a working 64bit build due to various 32bit dependencies in Xamarin Studio.  

Hopefully a full 64bit mono and Xamarin Studio in the future will make this experience better on OSX.
